// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsbppozksmixelqphgyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzYnBwb3prc21peGVscXBoZ3lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDgxNDQsImV4cCI6MjA3MjU4NDE0NH0.KjzC8lTociTJzH91Mq43KhdtHGRKYSofyfwOoKZQ-Ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});